# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background: pink")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.black_white_btn = QtWidgets.QPushButton(self.centralwidget)
        self.black_white_btn.setGeometry(QtCore.QRect(270, 450, 91, 81))
        self.black_white_btn.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.black_white_btn.setObjectName("black_white_btn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 256, 501))
        self.listWidget.setObjectName("listWidget")
        self.sharpness = QtWidgets.QPushButton(self.centralwidget)
        self.sharpness.setGeometry(QtCore.QRect(270, 370, 91, 61))
        self.sharpness.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.sharpness.setObjectName("sharpness")
        self.mirror = QtWidgets.QPushButton(self.centralwidget)
        self.mirror.setGeometry(QtCore.QRect(270, 290, 91, 61))
        self.mirror.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.mirror.setObjectName("mirror")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(270, 200, 91, 61))
        self.right.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.right.setObjectName("right")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(270, 120, 91, 61))
        self.left_btn.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.left_btn.setObjectName("left_btn")
        self.folder = QtWidgets.QPushButton(self.centralwidget)
        self.folder.setGeometry(QtCore.QRect(0, 0, 261, 31))
        self.folder.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.folder.setObjectName("folder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 30, 411, 521))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.black_white_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.sharpness.setText(_translate("MainWindow", "Різкість"))
        self.mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.right.setText(_translate("MainWindow", "Праворуч"))
        self.left_btn.setText(_translate("MainWindow", "Ліворуч"))
        self.folder.setText(_translate("MainWindow", "Папка"))
        self.label.setText(_translate("MainWindow", "Картинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
